import Link from "next/link";

const formatDate = (date) => new Intl.DateTimeFormat("en-IN", { day: "numeric", month: "long", year: "numeric" }).format(new Date(date));
function InfoGrid({ items }) { return <dl className="grid gap-px overflow-hidden rounded-xl border border-gray-200 bg-gray-200 sm:grid-cols-2">{items.filter((item) => item[1]).map(([label, value]) => <div key={label} className="bg-white p-4"><dt className="text-xs font-semibold uppercase tracking-wide text-gray-500">{label}</dt><dd className="mt-1 text-sm font-medium text-gray-900">{value}</dd></div>)}</dl>; }
function Section({ title, children }) { return <section className="mt-8 border-t border-gray-100 pt-7"><h2 className="text-xl font-bold text-gray-900">{title}</h2><div className="mt-3 text-sm leading-7 text-gray-600">{children}</div></section>; }
function Steps({ items }) { return <ol className="list-decimal space-y-2 pl-5">{items.map((item) => <li key={item}>{item}</li>)}</ol>; }

export default function ContentDetailLayout({ update, kind }) {
  const isJob = kind === "job"; const isAdmitCard = kind === "admit-card";
  const actionLabel = isJob ? "Apply on Official Website" : isAdmitCard ? "Download Admit Card" : "Check Result";
  const backHref = isJob ? "/jobs" : isAdmitCard ? "/admit-card" : "/results";
  const officialWebsite = update.officialWebsite || update.officialLink;
  const items = isJob ? [["Post Name", update.title], ["Organization", update.organization], ["Total Vacancies", update.vacancies], ["Application Mode", update.applicationMode], ["Eligibility", update.eligibility], ["Last Date", update.lastDate], ["Job Location", update.jobLocation], ["Salary / Pay", update.salary], ["Application Fee", update.applicationFee]] : [["Organization", update.organization], ["Exam", update.exam], [isAdmitCard ? "Admit Card Status" : "Result Status", isAdmitCard ? update.admitCardStatus : update.resultStatus], ["Exam Date", update.examDate], [isAdmitCard ? "Release Date" : "Result Date", isAdmitCard ? update.releaseDate : update.resultDate]];
  return <main className="min-h-screen bg-gray-50 px-4 pb-16 pt-24"><div className="mx-auto max-w-4xl"><Link href={backHref} className="text-sm font-semibold text-blue-700 hover:underline">← Back to updates</Link><article className="mt-5 rounded-2xl border border-gray-200 bg-white p-5 shadow-sm sm:p-8"><div className="flex flex-wrap items-center gap-3 text-sm"><span className="rounded-full bg-blue-50 px-3 py-1 font-semibold text-blue-700">{update.category}</span><time dateTime={update.publishedAt} className="text-gray-500">Published: {formatDate(update.publishedAt)}</time></div><h1 className="mt-4 text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">{update.title}</h1><p className="mt-4 text-base leading-7 text-gray-600">{update.shortDescription}</p><div className="mt-7"><InfoGrid items={items} /></div>
    <Section title="Official Links"><div className="flex flex-wrap gap-3">{officialWebsite && <a href={officialWebsite} target="_blank" rel="noopener noreferrer" className="inline-flex items-center rounded-lg border border-blue-200 bg-white px-4 py-3 text-sm font-semibold text-blue-700 transition hover:border-blue-400 hover:bg-blue-50 focus:outline-none focus:ring-2 focus:ring-blue-500">Official Website <span className="ml-2" aria-hidden="true">↗</span></a>}{update.officialLink && <a href={update.officialLink} target="_blank" rel="noopener noreferrer" className="inline-flex items-center rounded-lg bg-blue-700 px-4 py-3 text-sm font-semibold text-white transition hover:bg-blue-800 focus:outline-none focus:ring-2 focus:ring-blue-500">{actionLabel} <span className="ml-2" aria-hidden="true">↗</span></a>}</div>{!officialWebsite && !update.officialLink && <p className="rounded-lg border border-blue-100 bg-blue-50 p-4 text-sm text-blue-900">The official link will be added after verification. Always check the official notification before applying or downloading.</p>}<p className="mt-4 text-xs leading-5 text-gray-500">Verify the latest notification, eligibility, dates and application instructions on the official website before taking action.</p></Section>
  </article></div></main>;
}